<a href="https://colab.research.google.com/github/sammainahkinya1404/Machine-Learning-Algorithms/blob/main/Data_Manipulation_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# creating atensor
t=torch.arange(25,dtype=torch.float32)
t

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [3]:
# checking total number of elements in  tensor
t.numel()

25

In [4]:
# Checking the shape of a tensor(length of each axis in a tensor)
t.shape

torch.Size([25])

In [5]:
# Tensor transformation from a Vector(t(25)) to a Matix (T(5,5))
# t1=t.reshape(5,5)
# t1

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])

In [6]:
# or
# t1=t.reshape(-1,5)

# t1

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])

In [7]:
t1=t.reshape(5,-1)
t1

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])

In [8]:
# Zeros tensors(2,3,4)(x,y,z)(columns,rows,depth)
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# Ones Tensors(5,8,4)
torch.ones((5,8,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1.

In [10]:
# Creating a tensor with random elements
torch.randn(5,4)

tensor([[ 0.6976, -1.3591, -2.3883, -0.0239],
        [-0.8013, -1.7755,  1.2259, -1.0935],
        [ 0.0298,  0.4404, -0.5822, -0.6610],
        [-0.0181, -1.4445, -1.2082,  0.3454],
        [ 1.2123,  0.0865, -1.7182,  0.3909]])

In [11]:
# We can also create a tensor from scratch using Lists in python
torch.tensor([[4,2,1,3],[1,3,2,4],[3,2,4,1]])

tensor([[4, 2, 1, 3],
        [1, 3, 2, 4],
        [3, 2, 4, 1]])

As with Python lists, we can access tensor elements by indexing (starting with 0). To access an element based on its position relative to the end of the list, we can use negative indexing. Finally, we can access whole ranges of indices via slicing (e.g., X[start:stop]), where the returned value includes the first index (start) but not the last (stop). Finally, when only one index (or slice) is specified for a
-order tensor, it is applied along axis 0. Thus, in the following code, [-1] selects the last row and [1:3] selects the second and third rows.

In [13]:
# Slicing and Indexing
# Indexing accessing elements of a tensors starting by pointing to its exact location
t1[-1]

tensor([20., 21., 22., 23., 24.])

In [15]:
# Slicing getting a portion of the tensor by specifying the range
t1[1:3]

tensor([[ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [17]:
# Wring into the tensor by specifying the index of elemnt you want to alter/write
t1[1,3]=25
t1

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7., 25.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])

If we want to assign multiple elements the same value, we apply the indexing on the left-hand side of the assignment operation. For instance, [:2, :] accesses the first and second rows, where : takes all the elements along axis 1 (column). While we discussed indexing for matrices, this also works for vectors and for tensors of more than two dimensions.

In [23]:
t1[:3,:]=1456*456*0
t1

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])

In [24]:
torch.exp(t)

tensor([1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00, 3.2690e+06, 8.8861e+06, 2.4155e+07,
        6.5660e+07, 1.7848e+08, 4.8517e+08, 1.3188e+09, 3.5849e+09, 9.7448e+09,
        2.6489e+10])