<a href="https://colab.research.google.com/github/sammainahkinya1404/Machine-Learning-Algorithms/blob/main/Machine_Learning_Codes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Expected Mean

In [2]:
from numpy import array
from numpy import mean

In [9]:
arr=array([[1,2,3,4,5,6],[1,2,3,4,5,6]])

In [10]:
print(arr)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [11]:
results1=mean(arr , axis=0)

In [12]:
print(results1)

[1. 2. 3. 4. 5. 6.]


In [13]:
results2=mean(arr , axis=1)

In [14]:
print(results1)

[1. 2. 3. 4. 5. 6.]


In [18]:
# mean for the Matrix
results3=mean(arr)
results3

3.5

In [19]:
import numpy as np

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
# mean
mn=np.mean(matrix)
mn

2.0

In [20]:
# variance
variance=np.var(matrix)
variance

0.6666666666666666

In [23]:
# standard deviation
sd=np.std(matrix)
sd

0.816496580927726

In [24]:
# covariance
x=np.array([1,2,5,6,89,78,78])
x.shape
y=np.array([4,5,89,85,78,74,85])
y.shape

(7,)

In [26]:
# covariance
sigma=np.cov(x,y)[0,1]
sigma

795.5

In [28]:
# Correlation
sigma2=np.corrcoef(x,y)[0,1]
sigma2

0.49563680145148764