<a href="https://colab.research.google.com/github/sammainahkinya1404/Machine-Learning-Algorithms/blob/main/Machine_Learning_cookbook_recipes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# creating a vector
# we use a 1-d numpy array
# vector row
vector_row=np.array([1,2,3])
vector_row

array([1, 2, 3])

In [3]:
#vector_column
vector_column=np.array([[1],[2],[3]])
vector_column

array([[1],
       [2],
       [3]])

In [5]:
# Creating Matrix
# We use 2-d numpy array
matrix=np.array([[1,2],[1,5],[8,23]])
matrix

array([[ 1,  2],
       [ 1,  5],
       [ 8, 23]])

In [6]:
# Selecting Elements in a matrix and Vectors
vector_column[0]

array([1])

In [8]:
vector_row[2]

3

In [7]:
# Matric
matrix[2]

array([ 8, 23])

In [11]:
matrix[0,1]

2